config:
    paths:
        pim/job-execution-view: pimimportexport/js/job-execution-view
        pim/product-export/locales-selector: pimimportexport/js/product-export/locales-selector
        pim/product-export/updated-since-selector: pimimportexport/js/product-export/updated-since-selector
