parameters:
    pim_versioning.purger.version.class: Pim\Bundle\VersioningBundle\Purger\Purger
    pim_versioning.purger.advisor.base_purger.class: Pim\Bundle\VersioningBundle\Purger\BaseAdvisor
    pim_versioning.purger.advisor.number_of_days.class: Pim\Bundle\VersioningBundle\Purger\NumberOfDaysAdvisor

services:
    # Purger
    pim_versioning.purger.version:
        class: '%pim_versioning.purger.version.class%'
        arguments:
            - '@pim_versioning.repository.version'
            - '@akeneo_storage_utils.doctrine.object_detacher'

    # advisors
    pim_versioning.purger.advisor.base:
        class: '%pim_versioning.purger.advisor.base_purger.class%'
        arguments: ['@pim_versioning.repository.version']
        tags:
            - { name: pim_versioning.purger.advisor }

    pim_versioning.purger.advisor.number_of_days:
        class: '%pim_versioning.purger.advisor.number_of_days.class%'
        arguments: ['@pim_versioning.repository.version']
        tags:
            - { name: pim_versioning.purger.advisor }
