parameters:
    pim_versioning.purger.version.class: Pim\Bundle\VersioningBundle\Purger\VersionPurger
    pim_versioning.purger.voter.base_purger.class: Pim\Bundle\VersioningBundle\Purger\BasePurgeVoter
    pim_versioning.purger.voter.number_of_days.class: Pim\Bundle\VersioningBundle\Purger\BasePurgeVoter

services:
    # Purger
    pim_versioning.purger.version:
        class: '%pim_versioning.purger.version.class%'
        arguments:
            - '@pim_versioning.repository.version'
            - '@akeneo_storage_utils.doctrine.object_detacher'

    # Voters
    pim_versioning.purger.voter.base:
        class: '%pim_versioning.purger.voter.base_purger.class%'
        arguments: ['@pim_versioning.repository.version']
        tags:
            - { name: pim_versioning.purger.voter }

    pim_versioning.purger.voter.number_of_days:
        class: '%pim_versioning.purger.voter.number_of_days.class%'
        arguments: ['@pim_versioning.repository.version']
        tags:
            - { name: pim_versioning.purger.voter }
