parameters:
    pim_connector.validator.item.charset_validator.class: Pim\Component\Connector\Item\CharsetValidator

services:
    pim_connector.validator.item.charset_validator:
        class: %pim_connector.validator.item.charset_validator.class%
        arguments:
            - '@pim_connector.archive_storage'
