parameters:
    pim_connector.transfer.archive_to_local_transfer_step_element.class: Pim\Component\Connector\Transfer\ArchiveToLocalTransferStepElement

services:
    pim_connector.transfer.archive_to_local_transfer_step_element:
        class: '%pim_connector.transfer.archive_to_local_transfer_step_element.class%'
        arguments:
            - '@pim_connector.archive_storage'
